import * as Outlined from './outlined'
import * as Filled from './filled'
import type { SVGProps } from 'react'

export type IconName =
  | 'account_balance_wallet'
  | 'add'
  | 'add_circle'
  | 'apps'
  | 'arrow_back'
  | 'arrow_circle_up'
  | 'arrow_downward'
  | 'arrow_forward'
  | 'arrow_outward'
  | 'arrow_upward'
  | 'autorenew'
  | 'bolt'
  | 'bug_report'
  | 'call_received'
  | 'cancel'
  | 'check'
  | 'check_circle'
  | 'chevron_right'
  | 'close'
  | 'cloud_upload'
  | 'code'
  | 'content_copy'
  | 'content_paste'
  | 'currency_bitcoin'
  | 'delete'
  | 'delete_sweep'
  | 'description'
  | 'download'
  | 'edit'
  | 'error'
  | 'error_outline'
  | 'expand_less'
  | 'expand_more'
  | 'fingerprint'
  | 'folder_zip'
  | 'grid_view'
  | 'help'
  | 'hexagon'
  | 'history'
  | 'hourglass_top'
  | 'hub'
  | 'info'
  | 'inventory_2'
  | 'ios_share'
  | 'key'
  | 'layers'
  | 'link'
  | 'lock'
  | 'lock_open'
  | 'menu'
  | 'north_east'
  | 'open_in_new'
  | 'person'
  | 'power_settings_new'
  | 'qr_code_2'
  | 'qr_code_scanner'
  | 'radio_button_unchecked'
  | 'receipt_long'
  | 'refresh'
  | 'remove'
  | 'remove_circle'
  | 'restore'
  | 'rocket_launch'
  | 'schedule'
  | 'science'
  | 'chat_bubble'
  | 'event'
  | 'play_arrow'
  | 'psychology'
  | 'search'
  | 'settings'
  | 'shield'
  | 'smart_toy'
  | 'south_west'
  | 'swap_horiz'
  | 'swap_vert'
  | 'sync'
  | 'sync_alt'
  | 'timer'
  | 'timer_off'
  | 'token'
  | 'tune'
  | 'upload'
  | 'upload_file'
  | 'verified'
  | 'visibility'
  | 'visibility_off'
  | 'warning'
  | 'history_toggle_off'
  | 'payments'
  | 'toll'
  | 'trending_up'
  | 'touch_app'
  | 'dark_mode'
  | 'palette'

export const outlinedMap: Record<IconName, React.FC<SVGProps<SVGSVGElement>>> = {
  'account_balance_wallet': Outlined.AccountBalanceWallet,
  'add': Outlined.Add,
  'add_circle': Outlined.AddCircle,
  'apps': Outlined.Apps,
  'arrow_back': Outlined.ArrowBack,
  'arrow_circle_up': Outlined.ArrowCircleUp,
  'arrow_downward': Outlined.ArrowDownward,
  'arrow_forward': Outlined.ArrowForward,
  'arrow_outward': Outlined.ArrowOutward,
  'arrow_upward': Outlined.ArrowUpward,
  'autorenew': Outlined.Autorenew,
  'bolt': Outlined.Bolt,
  'bug_report': Outlined.BugReport,
  'call_received': Outlined.CallReceived,
  'cancel': Outlined.Cancel,
  'check': Outlined.Check,
  'check_circle': Outlined.CheckCircle,
  'chevron_right': Outlined.ChevronRight,
  'close': Outlined.Close,
  'cloud_upload': Outlined.CloudUpload,
  'code': Outlined.Code,
  'content_copy': Outlined.ContentCopy,
  'content_paste': Outlined.ContentPaste,
  'currency_bitcoin': Outlined.CurrencyBitcoin,
  'delete': Outlined.Delete,
  'delete_sweep': Outlined.DeleteSweep,
  'description': Outlined.Description,
  'download': Outlined.Download,
  'edit': Outlined.Edit,
  'error': Outlined.Error,
  'error_outline': Outlined.ErrorOutline,
  'expand_less': Outlined.ExpandLess,
  'expand_more': Outlined.ExpandMore,
  'fingerprint': Outlined.Fingerprint,
  'folder_zip': Outlined.FolderZip,
  'grid_view': Outlined.GridView,
  'help': Outlined.Help,
  'hexagon': Outlined.Hexagon,
  'history': Outlined.History,
  'hourglass_top': Outlined.HourglassTop,
  'hub': Outlined.Hub,
  'info': Outlined.Info,
  'inventory_2': Outlined.Inventory_2,
  'ios_share': Outlined.IosShare,
  'key': Outlined.Key,
  'layers': Outlined.Layers,
  'link': Outlined.Link,
  'lock': Outlined.Lock,
  'lock_open': Outlined.LockOpen,
  'menu': Outlined.Menu,
  'north_east': Outlined.NorthEast,
  'open_in_new': Outlined.OpenInNew,
  'person': Outlined.Person,
  'power_settings_new': Outlined.PowerSettingsNew,
  'qr_code_2': Outlined.QrCode_2,
  'qr_code_scanner': Outlined.QrCodeScanner,
  'radio_button_unchecked': Outlined.RadioButtonUnchecked,
  'receipt_long': Outlined.ReceiptLong,
  'refresh': Outlined.Refresh,
  'remove': Outlined.Remove,
  'remove_circle': Outlined.RemoveCircle,
  'restore': Outlined.Restore,
  'rocket_launch': Outlined.RocketLaunch,
  'schedule': Outlined.Schedule,
  'science': Outlined.Science,
  'chat_bubble': Outlined.ChatBubble,
  'event': Outlined.Event,
  'play_arrow': Outlined.PlayArrow,
  'psychology': Outlined.Psychology,
  'search': Outlined.Search,
  'settings': Outlined.Settings,
  'shield': Outlined.Shield,
  'smart_toy': Outlined.SmartToy,
  'south_west': Outlined.SouthWest,
  'swap_horiz': Outlined.SwapHoriz,
  'swap_vert': Outlined.SwapVert,
  'sync': Outlined.Sync,
  'sync_alt': Outlined.SyncAlt,
  'timer': Outlined.Timer,
  'timer_off': Outlined.TimerOff,
  'token': Outlined.Token,
  'tune': Outlined.Tune,
  'upload': Outlined.Upload,
  'upload_file': Outlined.UploadFile,
  'verified': Outlined.Verified,
  'visibility': Outlined.Visibility,
  'visibility_off': Outlined.VisibilityOff,
  'warning': Outlined.Warning,
  'history_toggle_off': Outlined.HistoryToggleOff,
  'payments': Outlined.Payments,
  'toll': Outlined.Toll,
  'trending_up': Outlined.TrendingUp,
  'touch_app': Outlined.TouchApp,
  'dark_mode': Outlined.DarkMode,
  'palette': Outlined.Palette,
}

export const filledMap: Partial<Record<IconName, React.FC<SVGProps<SVGSVGElement>>>> = {
  'account_balance_wallet': Filled.AccountBalanceWalletFilled,
  'check_circle': Filled.CheckCircleFilled,
  'history': Filled.HistoryFilled,
  'settings': Filled.SettingsFilled,
  'swap_horiz': Filled.SwapHorizFilled,
}
